const labMethodDefaultState = {
    name: '',
    where: '',
    isExt: '',
    syn: '',
    nameAk: '',
    groupAk: '',
    whenExtTransport: '',
    draw: '',
    preanal: '',
    note: '',
    customNote: '',
    parcelWho: '',
    parcelPreanal: '',
    parcelNote: '',
    extHowOften: '',
    extResponse: '',
    metodics: '',
    unit: '',
    expertise: '',
    refRange: '',
    rutCare: true,
    rutTime: '',
    statCare: false,
    statTime: '1h',
    erCare: false,
    erTime: '5h',
    additionalOrder: '',
    responseNote: '',
    interfereDown: '',
    interfereUp: '',
    physVar: '',
    bioHalfLife: ''
};

export default labMethodDefaultState;